# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TestService.proto

require 'google/protobuf'


descriptor_data = "\n\x11TestService.proto\"\t\n\x07TestReq\"\x18\n\x08TestResp\x12\x0c\n\x04host\x18\x01 \x01(\t2+\n\x0bTestService\x12\x1c\n\x03Run\x12\x08.TestReq\x1a\t.TestResp\"\x00\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

TestReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TestReq").msgclass
TestResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TestResp").msgclass
