# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TestService.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("TestService.proto", :syntax => :proto3) do
    add_message "TestReq" do
    end
    add_message "TestResp" do
      optional :host, :string, 1
    end
  end
end

TestReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TestReq").msgclass
TestResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TestResp").msgclass
